compatibility_date = "2025-01-01"
name = "ramesdev"
main = "backend/index.js"
workers_dev = false
account_id = "f6eb193c5ada002251ec96253583e74d"

routes = [
  { pattern = "rames.dev/*", zone_name = "rames.dev" },
  { pattern = "demo.rames.dev/*", zone_name = "rames.dev" },
  { pattern = "utils.rames.dev/*", zone_name = "rames.dev" },
  { pattern = "serve.rames.dev/*", zone_name = "rames.dev" },
  { pattern = "clip.rames.dev/*", zone_name = "rames.dev" },
]

[assets]
directory = "./frontend"
binding = "ASSETS"

[vars]
ENV_JWKS_CACHE_USE = true
ENV_JWKS_CACHE_KEY = "JWKS_CACHE"
ENV_JWKS_CACHE_TTL = 604800 # a week: 7 * 24 * 60 * 60

[[kv_namespaces]]
binding = "KV_DATA"
id = "eca7dea9758d4f2a97ba727c048b53f0"

[[kv_namespaces]]
binding = "KV_CLIP"
id = "1286e18d5328468c8a98e05898efeffe"
